config:
  send_anonymous_usage_stats: False

example_shop:
  target: staging
  outputs:
    prod:
      type: fal
      db_profile: prod_db

    staging:
      type: fal
      db_profile: staging_db

    staging_db:
      type: postgres
      host: localhost
      user: pguser
      password: pass
      port: 5432
      dbname: test
      schema: dbt_fal
      threads: 4

    prod_db:
      type: redshift
      host: "{{ env_var('RS_HOST') }}"
      port: 5439
      user: "{{ env_var('RS_USER') }}"
      password: "{{ env_var('RS_PASSWORD') }}"
      dbname: "{{ env_var('RS_DBNAME') }}"
      schema: "{{ env_var('RS_SCHEMA') }}"
      threads: 4
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 20 # default 10 seconds
      ra3_node: false

